name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - "locked"
          - "highest"
          - "lowest"
        laravel:
          - "6.x"
          - "7.x"
          - "8.x"
        experimental:
          - false

    name: Laravel ${{ matrix.laravel }} on PHP${{ matrix.php }}-${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath, fileinfo
          coverage: none

      - name: Install Laravel Framework ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist"
      - name: Execute tests
        run: vendor/bin/phpunit

  tests-on-legacy-setup:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "7.2"
        dependencies:
          - "locked"
          - "highest"
          - "lowest"
        laravel:
          - "5.8.x"
          - "6.x"
          - "7.x"
        experimental:
          - false
        include:
          - os: "ubuntu-latest"
            php: "7.1"
            dependencies: "locked"
            laravel: "5.8.x"
          - os: "ubuntu-latest"
            php: "7.1"
            dependencies: "highest"
            laravel: "5.8.x"
          - os: "ubuntu-latest"
            php: "7.1"
            dependencies: "lowest"
            laravel: "5.8.x"

    name: Laravel ${{ matrix.laravel }} on PHP${{ matrix.php }}-${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath, fileinfo
          coverage: none

      - name: Install Laravel Framework ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist"
      - name: Execute tests
        run: vendor/bin/phpunit
